# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
    ]
