# Generated by Django 3.0.2 on 2020-01-17 19:44

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpublic', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Número de referencia')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
    ]
